apiVersion: apps/v1
kind: Deployment
metadata:
  name: decase
  namespace: sk-team-08
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decase
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
        prometheus.io/path: '/actuator/prometheus'
        update: 5e59d2ee47d1c85987208efb0e91a711
      labels:
        app: decase
    spec:
      serviceAccountName: default
      containers:
      - name: webserver
        image: amdp-registry.skala-ai.com/skala25a/sk-team-08-decase:1.0.0-5-9660ec742e9d
        imagePullPolicy: Always
        env:
        - name: MARIA_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: decase-secret
              key: MARIA_DATABASE_URL
        - name: MARIA_USER
          valueFrom:
            secretKeyRef:
              name: decase-secret
              key: MARIA_USER
        - name: MARIA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: decase-secret
              key: MARIA_PASSWORD
        - name: MAIL_ADDRESS
          valueFrom:
            secretKeyRef:
              name: decase-secret
              key: MAIL_ADDRESS
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: decase-secret
              key: MAIL_PASSWORD
        envFrom:
        - secretRef:
            name: decase-secret